In [20]:
import numpy as np

# create an emtpy list
my_list = []

# populate list with the first 50 even numbers
for i in range(200):
    # if list contains 50 numbers stop
    if len(my_list) < 50:
        # check if number is even
        if i%2 == 0:
            # append number to list
            my_list.append(i)
            
# print an informative message
print("My list contains the following {} numbers:\n\n{}\n".
      format(len(my_list), my_list))

# convert list to a numpy array
my_array = np.array(my_list)
print("My list is now converted into a numPy array with a shape of {}:\n\n{}\n".
      format(my_array.shape, my_array))

# convert 1D np array to a 2D (10x5) np array
my_2d_array = np.reshape(my_array, (10, 5))
print("My 1D np array is now converted into a numPy array with a shape of {}:\n\n{}\n".
      format(my_2d_array.shape, my_2d_array))

# transpose the 2d np array from (10x5) to (5x10)
my_trans_array = np.transpose(my_2d_array)
print("My transposed 2D np array has now a shape of {}:\n\n{}".format(my_trans_array.shape, my_trans_array))

My list contains the following 50 numbers:

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]

My list is now converted into a numPy array with a shape of (50,):

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]

My 1D np array is now converted into a numPy array with a shape of (10, 5):

[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]
 [50 52 54 56 58]
 [60 62 64 66 68]
 [70 72 74 76 78]
 [80 82 84 86 88]
 [90 92 94 96 98]]

My transposed 2D np array has now a shape of (5, 10):

[[ 0 10 20 30 40 50 60 70 80 90]
 [ 2 12 22 32 42 52 62 72 82 92]
 [ 4 14 24 34 44 54 64 74 84 94]
 [ 6 16 26 36 46 56 66 76 86 96]
 [ 8 18 28 38 48 58 68 78 88 98]]
